spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/covid-db"
    username: admin
    password: admin

secret-key: secret

server:
  port: 8081

auth:
  base-url: http://localhost:8080
  path: /api/v1/authenticate
